Repository andrewjswan/pixel-clock, pull requests merged in 2025-07, with the labels that each got.

#5 Switch to EspHoMaTriX 2025.6.3
  .github/workflows/release.yaml
  packages/pixel_clock.yaml
Labels: extra small, stability/medium, dependencies

#8 Update pixel_clock.yaml add pullup to left and right button
  packages/pixel_clock.yaml
Labels: extra small, stability/medium

#10 EspHoMaTriX: 2025.7.1
  packages/common.yaml
  packages/pixel_clock.yaml
  packages/pixel_clock_timezone.yaml
  pixel_clock.yaml
  pixel_clock_en.yaml
  pixel_clock_ru.yaml
Labels: enhancement, small, stability/medium, dependencies

#12 Flip local font to trip5 Matrix-Fonts repo
  packages/pixel_clock.yaml
Labels: extra small, stability/medium, dependencies
